### ISSUE TITLE
Gaurav : Can't Hurt Me 

### ISSUE THREAD

**Issue by EuclidStellar** [USKhokhar/fehrist#18]
## Book Title?
Can't Hurt Me

## Author?
David Goggins

## Genre of Book?
Non-Fiction

**Comment by Alexpeain** [comment]
I would like to work for this project.

**Comment by EuclidStellar** [comment]
> I would like to work for this project.

what will be your appoach to make this work?

**Comment by Alexpeain** [comment]
I might need to follow how to contribute such as fork it ,install npm package ,npx add .
I think I can do this even there might be some challenges.

**Comment by EuclidStellar** [comment]
> I might need to follow how to contribute such as fork it ,install npm package ,npx add .
> I think I can do this even there might be some challenges.
Nice, I loved your enthusiasm 
Go for it !!! 🚀

**Comment by EuclidStellar** [comment]
🚀🚀🚀🚀

**Comment by USKhokhar** [comment]
Hey @Alexpeain ! I've assigned this to you... you can proceed with this one 🚀

**Comment by USKhokhar** [comment]
#26
