### ISSUE TITLE
Lessons In Chemistry

### ISSUE THREAD

**Issue by 86pushkar24** [USKhokhar/fehrist#33]
## Book Title?
Lessons In Chemistry

## Author?
Bonnie Garmus 

## Genre of Book?
Historical Fiction

**Comment by USKhokhar** [comment]
Assigned this to you @86pushkar24 🚀

**Comment by DanielZhang111** [comment]
Can I also get assigned?

**Comment by USKhokhar** [comment]
> Can I also get assigned?

Hey @DanielZhang111 , this issue has been closed but you can raise a new issue for any other book. Please read the Contribution Guidelines

**Comment by DanielZhang111** [comment]
Ok thanks
