### ISSUE TITLE
Mohit Bharti : Mein Kampf

### ISSUE THREAD

**Issue by themohitbharti** [USKhokhar/fehrist#35]
## Book Title?
Mein Kampf

## Author?
Adolf Hitler

## Genre of Book?
Auto Biography

**Comment by dakshsinghrathore** [comment]
Hey @themohitbharti Kindly assign this issue to me.

**Comment by USKhokhar** [comment]
> Hey @themohitbharti Kindly assign this issue to me.

Hey @dakshsinghrathore , a PR already exists for this issue. You can raise a PR for any other book. More in [Contribution Guidelines](https://github.com/USKhokhar/fehrist/blob/master/CONTRIBUTING.md)

**Comment by USKhokhar** [comment]
#36
