### ISSUE TITLE
Tanishka: The 48 Laws of Power

### ISSUE THREAD

**Issue by Tanishka0067** [USKhokhar/fehrist#45]
## Book Title?
The 48 Laws of Power

## Author?
Robert Greene

## Genre of Book?
Self-help

**Comment by pranavjainjs** [comment]
Hi, I'd like to add the synopsis of 48 Laws of Power.

**Comment by USKhokhar** [comment]
> Hi, I'd like to add the synopsis of 48 Laws of Power.

Hi @pranavjainjs , you can add for any other book. More in [Contribution Guidelines](https://github.com/USKhokhar/fehrist/blob/master/CONTRIBUTING.md)

**Comment by USKhokhar** [comment]
> can u explain me the issue a bit more @Tanishka0067 

Hey @adarsht0001 , please read [README](https://github.com/USKhokhar/fehrist/blob/master/README.md) to know more about the project.
