### ISSUE TITLE
Mohit: Why I killed Gandhi

### ISSUE THREAD

**Issue by themohitbharti** [USKhokhar/fehrist#46]
## Book Title?
Why I Killed Gandhi.

## Author?
Nathuram Godse

## Genre of Book?
non-fiction

**Comment by themohitbharti** [comment]
> can u explain me the issue a bit more

Certainly. "Why I Killed Gandhi" is a highly controversial book written by Nathuram Godse, the man who assassinated Mahatma Gandhi, a revered leader in the Indian independence movement. The book offers Godse's perspective on the assassination and attempts to justify his actions and ideological differences with Gandhi.

**Comment by USKhokhar** [comment]
> can u assign me @themohitbharti 

Hey @adarsht0001 you can do the same for any other book of your choice. Please refer README

**Comment by USKhokhar** [comment]
> can u assign me @themohitbharti 

Hey @adarsht0001 you can do the same for any other book of your choice. Please refer README
