### ISSUE TITLE
Tanishka: The Art Of Manipulation: How to Get Anybody to Do What You Want

### ISSUE THREAD

**Issue by Tanishka0067** [USKhokhar/fehrist#47]
## Book Title?
The Art Of Manipulation: How to Get Anybody to Do What You Want

## Author?
Omar Johnson

## Genre of Book?
Non-Fiction

**Comment by USKhokhar** [comment]
Assigned this to you @Tanishka0067 🚀

**Comment by USKhokhar** [comment]
Assigned this to you @Tanishka0067 🚀
