### ISSUE TITLE
Add Metamorphosis by Franz Kafka

### ISSUE THREAD

**Issue by pranavjainjs** [USKhokhar/fehrist#55]
## Book Title?
[Metamorphosis]

## Author?
[Franz Kafka]

## Genre of Book?
[Absurdist Fiction]

**Comment by Harsh-00** [comment]
Hello, I'm interested in working on this issue. Could you please assign it to me?

**Comment by USKhokhar** [comment]
Hey @pranavjainjs! Assigned this to you 🚀

**Comment by USKhokhar** [comment]
> Hello, I'm interested in working on this issue. Could you please assign it to me?

Hey @Harsh-00 ! You can raise an issue for another book.
